ALTER TABLE `beer`
	CHANGE COLUMN `Id` `id` INT(11) NOT NULL AUTO_INCREMENT FIRST,
	CHANGE COLUMN `Name` `name` VARCHAR(50) NULL DEFAULT '' AFTER `id`,
	CHANGE COLUMN `IdCategory` `idCategory` INT(11) NULL DEFAULT '1' AFTER `name`,
	CHANGE COLUMN `Graduation` `graduation` DECIMAL(10,2) NULL DEFAULT '0.00' AFTER `idCategory`;
